spring.application.name=customer-management-stored-procedure

# Example for a MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/customer_management
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keeps Spring from throwing an error if the database isn't fully ready at startup
spring.jpa.hibernate.ddl-auto=update
